---
# fs handler file for local_role

- name: Create extra symlinks
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  loop:
    - { src: ~/.files, dest: ~/wksc/dotfiles }
    - { src: ~/.zshrc_aliases, dest: ~/.bash_aliases }
    - { src: ~/.config/nvim/lua/custom, dest: ~/wksc/nvim-configs }
